### ISSUE TITLE
Does not update

### ISSUE THREAD

**Issue by jedifunk** [pocorschi/gatsby-plugin-google-fonts-v2#1]
Was having an issue with the fonts not loading in. Have it successfully working on another project. Checked versions. One version is 0.0.3, the other is 0.0.5.

ran `npm outdated` and see that a 0.0.6 version is available. Run `npm update` but version stays at 0.0.3.

**Comment by pocorschi** [comment]
@jedifunk  just checked and it should work. Worse case just
`yarn remove gatsby-plugin-google-fonts-v2` and then `yarn add gatsby-plugin-google-fonts-v2`
and it should install the latest version. Let me know if that works for you.

**Comment by jedifunk** [comment]
i'm not using yarn, just npm.

**Comment by pocorschi** [comment]
True. I'll take a look at that at the next version upgrade. I'll close the issue for now if that's ok with you.
