### ISSUE TITLE
Add instructions/support for using more than one fonts and font weights

### ISSUE THREAD

**Issue by tristandenyer** [pocorschi/gatsby-plugin-google-fonts-v2#2]
I followed your docs, and extended the options to include a second font with 2 font weights, but it creates a malformed request:
` https://fonts.googleapis.com/css2?family=Roboto:wght@500&family=Open+Sans:wght@&display=swap`

<img width="999" alt="Screen Shot 2020-04-20 at 9 34 48 PM" src="https://user-images.githubusercontent.com/4358288/79825760-d0ae6800-834e-11ea-8d35-13017802c67b.png">

I tried it this way, and it doesn't work.
```
{
      resolve: `gatsby-plugin-google-fonts-v2`,
      options: {
        fonts: [
          {
            family: 'Roboto',
            weights: ['500']
          },
          {
            family: 'Open+Sans',
            weights: [400, 700]
          }
        ]
      }
    }
```

The following does work:
```
{
            family: 'Roboto',
            weights: ['500']
          },
          {
            family: 'Open+Sans',
            weights: ['700']
}
```

And this works (but the request is not formatted like Google prefers):
```
{
            family: 'Open+Sans',
            weights: ['400']
          },
          {
            family: 'Open+Sans',
            weights: ['700']
          },
          {
            family: 'Roboto',
            weights: ['500']
 }
```

If your plugin supports multiple fonts + font weights, please provide an example in docs/README. If it doesn't support it, please consider this a request to support more than one font family.

**Comment by pocorschi** [comment]
Hi Tristan

This should work

`fonts:  [
      {
        family: 'Roboto',
        weights: ['500']
      },
      {
        family: 'Open Sans',
        weights: ['400', '700']
      }
]`
It returns a correctly formatted link:  
`https://fonts.googleapis.com/css2?family=Roboto:wght@500&family=Open+Sans:wght@400;700`

Please let me know if that works for you. I just added a test case covering multiple fonts and there should be no issue.

PS. You can forgo the '+' in the font name. It's automatically handled. If you want to pass the exact font name you can use `strictName: true`

**Comment by tristandenyer** [comment]
I used your latest suggestion and it worked, thx! Also updated README to reflect this suggestion.
